<a href="https://colab.research.google.com/github/LavanyaMQuantumThinker/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy -Numerical Python

Numpy better than List
-Faster- contigous(side-by-side) memory

1. Memory Efficient
2. Convenience
3. MultiDimensional Arrays
4. Rich Mathematical
5. Statistical Funtions

In [ ]:
!pip install numpy

In [ ]:
import numpy as np


In [ ]:
#creating 1D array
n1= np.array([1,2,3,4])
print(n1)

[1 2 3 4]


In [ ]:
#creating 2D array
n2 = np.array([[1,2,3,4],[5,6,7,8]])
print(n2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Zero Filled 2D array
n3= np.zeros([3,3])
n3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Here 0 is created as floating point so "0." is created -To over come this next step will help

In [ ]:
n3 = np.zeros([3,3],dtype = "int32")
print(n3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
n4 = np.ones([3,3],dtype= "int32")
print(n4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#Creating 3D array
n5=np.ones([2,3,3],dtype="int32")
print(n5)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


This creates 3Dimensional Array -- It seems 2 Times 2D array created and it is also present in a array--so totally 3 array combinely creating 3D array

In [ ]:
#Empty array
n5= np.empty([2,3])
print (n5)

[[2.61417004e-315 0.00000000e+000 2.68311345e-315]
 [1.63041663e-322 2.71572929e-315 6.64795013e-310]]
